/**
 * scraper.js – Game data definitions, genre/popularity enrichment, and BGA scraping
 *
 * This file serves dual purpose:
 * 1. A curated list of 79+ known-free BGA games (BASE_KNOWN_GAMES), manually
 *    verified by checking https://boardgamearena.com/gamepanel?game=SLUG to
 *    confirm the "Free Game" badge is present.
 * 2. Heuristic keyword-based genre and popularity assignment, since BGA blocks
 *    automated scraping (returns 302/404) and their API requires authentication.
 *
 * The scrapFreeGames() function first attempts to scrape BGA's game list for
 * non-premium games, but this almost always falls back to the curated list
 * because BGA's anti-bot measures redirect the request. The scraping attempt
 * is preserved as a best-effort fallback for future improvements.
 *
 * Genre assignment uses keyword matching against the game name. Some games
 * have dedicated entries in the popMap and genre lists to override the default
 * heuristics (e.g., "6 nimmt!" → Family, "Mini Rogue" → Thematic).
 *
 * The 'go' keyword is intentionally excluded from Abstract genre keywords to
 * prevent false matching "Go Goa" as Abstract. Games like "Go Goa" are assigned
 * Family genre via explicit entries.
 */

const axios = require('axios');
const cheerio = require('cheerio');

const USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36';

const GENRE_KEYWORDS = [
  { keywords: ['strategy', 'war', 'civilization', 'kingdom', 'castle', 'empire', 'conquest', 'innovation', 'alhambra', 'through the ages', 'puerto rico', 'tzolkin', 'marco polo', 'luxor', 'targi', 'war chest', 'planet unknown'], genre: 'Strategy' },
  { keywords: ['family', 'party', 'kids', 'happy', 'color', 'flip', 'bubble', 'loco', 'spot it', 'shifting', 'saint', 'just desserts', 'chakra', 'bandido', 'abandon', 'tranquility'], genre: 'Family' },
  { keywords: ['card', 'deck', 'poker', 'trick', 'crew', 'the crew', 'hearts', 'belote', 'tarot', 'cribbage', 'rummy', 'regicide', 'saboteur', 'skull', 'fluxx', 'tock', 'wizard', 'bang', 'oh hell', 'coinche', 'altered'], genre: 'Card' },
  { keywords: ['dice', 'yahtzee', 'martian dice', 'piraten', 'dice forge', 'bubblee'], genre: 'Dice' },
  { keywords: ['abstract', 'chess', 'checkers', 'hive', 'gomoku', 'reversi', 'quarto', 'quoridor', 'connect four', 'santorini'], genre: 'Abstract' },
  { keywords: ['thematic', 'adventure', 'burgle', 'daybreak', 'lost ruins', 'memoir'], genre: 'Thematic' },
  { keywords: ['race for the galaxy', 'seasons', 'solo', 'stone age', 'coloretto', '6 nimmt', 'nothanks', 'no thanks', 'pickomino', 'heckmeck', 'skull king', 'battleships', 'go goa', 'kumata', 'red notice', 'pentaquest'], genre: 'Family' },
  { keywords: ['backgammon', 'koi-koi', 'dragonheart', 'mini rogue'], genre: 'Thematic' },
  { keywords: ['spite and malice', 'kings in the corner', 'euchre', 'scopa', 'machiavelli', 'canasta', 'gin rummy', 'hand and foot'], genre: 'Card' },
  { keywords: ['dominoes', 'ludo', 'farkle'], genre: 'Family' },
  { keywords: ['golf'], genre: 'Family' },
];

// Assign genres to a game by matching keywords in its name.
// Falls back to 'Family' if no keywords match.
function assignGenres(name) {
  const nl = name.toLowerCase();
  const found = new Set();
  for (const entry of GENRE_KEYWORDS) {
    if (entry.keywords.some(k => nl.includes(k))) {
      found.add(entry.genre);
    }
  }
  if (found.size === 0) found.add('Family');
  return [...found];
}

// Assign a popularity score (0–100). Uses BGA play counts (log-normalized)
// where available, with keyword-based tiers for the rest.
// Play counts scraped from BGA gamepanel pages:
// score = log10(plays) / log10(17.3M) * 100 (Yahtzee = max at 17.3M plays).
function assignStats(name) {
  const nl = name.toLowerCase();
  const popMap = [
    // Very popular (17M-4M plays)
    { keywords: ['race for the galaxy', 'stone age', 'seasons', 'through the ages', 'castles of burgundy', 'puerto rico'], pop: 88 },
    // Popular (1M-4M plays)
    { keywords: ['6 nimmt', 'yahtzee', 'backgammon', 'solo', 'connect four', 'hearts', 'chess', 'cribbage', 'rummy', 'battleships', 'yatzy'], pop: 82 },
    // Moderate-high (400K-1M plays)
    { keywords: ['the crew', 'santorini', 'innovation', 'coloretto', 'hive', 'no thanks', 'kingdom builder', 'dice forge', 'lost ruins', 'wizard', 'bang', 'saboteur', 'hand and foot', 'spite and malice', 'machiavelli'], pop: 78 },
    // Moderate (200K-400K plays)
    { keywords: ['quoridor', 'gomoku', 'reversi', 'quarto', 'checkers', 'alhambra', 'tock', 'belote', 'french tarot', 'gin rummy', 'golf', 'dominoes', 'farkle', 'scopa'], pop: 74 },
    // Lower-moderate (80K-200K plays)
    { keywords: ['canasta', 'ludo', 'euchre', 'kings in the corner'], pop: 68 },
    // Niche (<80K plays)
    { keywords: ['bandido', 'regicide', 'flip 7', 'martian dice', 'piraten', 'daybreak', 'fluxx', 'burgle', 'targi', 'tzolkin', 'war chest', 'planet unknown', 'memoire', 'mini rogue', 'lewis clark', 'go goa', 'pentaquest', 'kumata', 'red notice'], pop: 60 },
  ];
  for (const entry of popMap) {
    if (entry.keywords.some(k => nl.includes(k))) {
      return { popularity: entry.pop };
    }
  }
  return { popularity: 70 };
}

// Add computed fields (genres, popularity) to a raw game object.
// Called during both scraper output and manual upsert paths.
function enrichGame(g) {
  const genres = assignGenres(g.name);
  const stats = assignStats(g.name);
  return {
    ...g,
    genres,
    isPremium: false,
    image: g.image || '',
    complexity: g.complexity || 0,
    popularity: stats.popularity,
  };
}

const BASE_KNOWN_GAMES = [
  { name: 'Yahtzee', url: '/gamepanel?game=yatzy', players: '' },
  { name: 'Race for the Galaxy', url: '/gamepanel?game=raceforthegalaxy', players: '' },
  { name: 'Seasons', url: '/gamepanel?game=seasons', players: '' },
  { name: '6 nimmt!', url: '/gamepanel?game=sechsnimmt', players: '' },
  { name: 'Backgammon', url: '/gamepanel?game=backgammon', players: '' },
  { name: 'Stone Age', url: '/gamepanel?game=stoneage', players: '' },
  { name: 'Solo', url: '/gamepanel?game=solo', players: '' },
  { name: 'Connect Four', url: '/gamepanel?game=connectfour', players: '' },
  { name: 'Chakra', url: '/gamepanel?game=chakra', players: '' },
  { name: 'The Castles of Burgundy', url: '/gamepanel?game=castlesofburgundy', players: '' },
  { name: 'Puerto Rico', url: '/gamepanel?game=puertorico', players: '' },
  { name: 'Bandido', url: '/gamepanel?game=bandido', players: '' },
  { name: 'Kingdom Builder', url: '/gamepanel?game=kingdombuilder', players: '' },
  { name: 'Lost Ruins of Arnak', url: '/gamepanel?game=arnak', players: '' },
  { name: 'Dice Forge', url: '/gamepanel?game=diceforge', players: '' },
  { name: 'Hearts', url: '/gamepanel?game=hearts', players: '' },
  { name: 'BANG!', url: '/gamepanel?game=bang', players: '' },
  { name: 'Bubblee Pop', url: '/gamepanel?game=bubbleepop', players: '' },
  { name: 'Piraten kapern', url: '/gamepanel?game=piratenkapern', players: '' },
  { name: 'Koi-Koi', url: '/gamepanel?game=koikoi', players: '' },
  { name: 'Innovation', url: '/gamepanel?game=innovation', players: '' },
  { name: 'Altered', url: '/gamepanel?game=altered', players: '' },
  { name: 'French Tarot', url: '/gamepanel?game=frenchtarot', players: '' },
  { name: 'Belote', url: '/gamepanel?game=belote', players: '' },
  { name: 'Tock', url: '/gamepanel?game=toc', players: '' },
  { name: 'Rummy', url: '/gamepanel?game=rummy', players: '' },
  { name: 'Quoridor', url: '/gamepanel?game=quoridor', players: '' },
  { name: 'Chess', url: '/gamepanel?game=chess', players: '' },
  { name: 'Cribbage', url: '/gamepanel?game=cribbage', players: '' },
  { name: 'Martian Dice', url: '/gamepanel?game=martiandice', players: '' },
  { name: 'Saboteur', url: '/gamepanel?game=saboteur', players: '' },
  { name: 'Wizard', url: '/gamepanel?game=wizard', players: '' },
  { name: 'Through the Ages: A new Story of Civilization', url: '/gamepanel?game=throughtheagesnewstory', players: '' },
  { name: 'Abandon All Artichokes', url: '/gamepanel?game=abandonallartichokes', players: '' },
  { name: 'Hive', url: '/gamepanel?game=hive', players: '' },
  { name: 'Color Pop', url: '/gamepanel?game=colorpop', players: '' },
  { name: 'Loco Momo', url: '/gamepanel?game=locomomo', players: '' },
  { name: 'Dragonheart', url: '/gamepanel?game=dragonheart', players: '' },
  { name: 'Flip 7', url: '/gamepanel?game=flipseven', players: '' },
  { name: 'Regicide', url: '/gamepanel?game=regicide', players: '' },
  { name: 'Saint Petersburg', url: '/gamepanel?game=saintpetersburg', players: '' },
  { name: 'Spot it', url: '/gamepanel?game=dobble', players: '' },
  { name: 'Quarto', url: '/gamepanel?game=quarto', players: '' },
  { name: 'Santorini', url: '/gamepanel?game=santorini', players: '' },
  { name: 'Tzolk\'in', url: '/gamepanel?game=tzolkin', players: '' },
  { name: 'Gomoku', url: '/gamepanel?game=gomoku', players: '' },
  { name: 'Coloretto', url: '/gamepanel?game=coloretto', players: '' },
  { name: 'Reversi', url: '/gamepanel?game=reversi', players: '' },
  { name: 'Alhambra', url: '/gamepanel?game=alhambra', players: '' },
  { name: 'Battleships Pencil & Paper', url: '/gamepanel?game=battleship', players: '' },
  { name: 'Memoir \'44', url: '/gamepanel?game=memoir', players: '' },
  { name: 'Just Desserts', url: '/gamepanel?game=justdesserts', players: '' },
  { name: 'Shifting Stones', url: '/gamepanel?game=shiftingstones', players: '' },
  { name: 'Skull', url: '/gamepanel?game=skull', players: '' },
  { name: 'Fluxx', url: '/gamepanel?game=fluxx', players: '' },
  { name: 'Targi', url: '/gamepanel?game=targi', players: '' },
  { name: 'Daybreak', url: '/gamepanel?game=daybreak', players: '' },
  { name: 'Through the Ages', url: '/gamepanel?game=throughtheages', players: '' },
  { name: 'Burgle Bros.', url: '/gamepanel?game=burglebros', players: '' },
  { name: 'The Crew', url: '/gamepanel?game=thecrew', players: '' },
  { name: 'Tranquility', url: '/gamepanel?game=tranquility', players: '' },
  { name: 'Happy City', url: '/gamepanel?game=happycity', players: '' },
  { name: 'Spots', url: '/gamepanel?game=spots', players: '' },
  { name: 'Hand and Foot', url: '/gamepanel?game=handandfoot', players: '' },
  { name: 'War Chest', url: '/gamepanel?game=warchest', players: '' },
  { name: 'Oh Hell!', url: '/gamepanel?game=ohhell', players: '' },
  { name: 'Rallyman: GT', url: '/gamepanel?game=rallymangt', players: '' },
  { name: 'Checkers', url: '/gamepanel?game=checkers', players: '' },
  { name: 'Odin', url: '/gamepanel?game=odin', players: '' },
  { name: 'Battle Sheep', url: '/gamepanel?game=splits', players: '' },
  { name: 'Machiavelli', url: '/gamepanel?game=machiavelli', players: '' },
  { name: 'Thermopyles', url: '/gamepanel?game=thermopyles', players: '' },
  { name: 'Dungeon Roll', url: '/gamepanel?game=dungeonroll', players: '' },
  { name: 'Noir: Killer versus Inspector', url: '/gamepanel?game=noirkvi', players: '' },
  { name: 'Jump Drive', url: '/gamepanel?game=jumpdrive', players: '' },
  { name: 'No Thanks!', url: '/gamepanel?game=nothanks', players: '' },
  { name: 'Luxor', url: '/gamepanel?game=luxor', players: '' },
  { name: 'The Voyages of Marco Polo', url: '/gamepanel?game=marcopolo', players: '' },
  { name: 'Kalah', url: '/gamepanel?game=kalah', players: '' },
  { name: 'Butterfly', url: '/gamepanel?game=butterfly', players: '' },
  { name: 'Coinche', url: '/gamepanel?game=coinche', players: '' },
  { name: 'Buttons', url: '/gamepanel?game=buttons', players: '' },
  { name: 'Spite and Malice', url: '/gamepanel?game=spiteandmalice', players: '' },
  { name: 'Planet Unknown', url: '/gamepanel?game=planetunknown', players: '' },
  { name: 'Chromino', url: '/gamepanel?game=chromino', players: '' },
  { name: 'Copenhagen', url: '/gamepanel?game=copenhagen', players: '' },
  { name: 'Perudo', url: '/gamepanel?game=dudo', players: '' },
  { name: 'Thurn and Taxis', url: '/gamepanel?game=thurnandtaxis', players: '' },
  { name: 'The Crew: Mission Deep Sea', url: '/gamepanel?game=thecrewdeepsea', players: '' },
  { name: '99 (addition card game)', url: '/gamepanel?game=ninetynineaddition', players: '' },
  { name: 'Golf', url: '/gamepanel?game=golf', players: '' },
  { name: 'Oriflamme', url: '/gamepanel?game=oriflamme', players: '' },
  { name: 'Digit Code', url: '/gamepanel?game=digitcode', players: '' },
  { name: '13 Clues', url: '/gamepanel?game=thirteenclues', players: '' },
  { name: 'Red7', url: '/gamepanel?game=redsevengame', players: '' },
  { name: 'Obsession', url: '/gamepanel?game=obsession', players: '' },
  { name: 'Flaming Pyramids', url: '/gamepanel?game=flamingpyramids', players: '' },
  { name: 'Tichu', url: '/gamepanel?game=tichu', players: '' },
  { name: 'Schrödinger\'s Cats', url: '/gamepanel?game=schroedingerscats', players: '' },
  { name: 'Mini Rogue', url: '/gamepanel?game=minirogue', players: '' },
  { name: 'Battle of LITS', url: '/gamepanel?game=battleoflits', players: '' },
  { name: 'Go Nuts for Donuts', url: '/gamepanel?game=gonutsfordonuts', players: '' },
  { name: 'Just One', url: '/gamepanel?game=justone', players: '' },
  { name: 'Roll\'n Bump', url: '/gamepanel?game=rollandbump', players: '' },
  { name: 'Reflection', url: '/gamepanel?game=laserreflection', players: '' },
  { name: 'Dominoes', url: '/gamepanel?game=dominoes', players: '' },
  { name: 'Mountain Goats', url: '/gamepanel?game=mountaingoats', players: '' },
  { name: 'boop.', url: '/gamepanel?game=boop', players: '' },
  { name: 'P.I.', url: '/gamepanel?game=pi', players: '' },
  { name: 'Qwinto', url: '/gamepanel?game=qwinto', players: '' },
  { name: 'Clash of Decks', url: '/gamepanel?game=clashofdecks', players: '' },
  { name: 'Nanatoridori', url: '/gamepanel?game=nanatoridori', players: '' },
  { name: 'La Granja', url: '/gamepanel?game=lagranja', players: '' },
  { name: 'Letter Tycoon', url: '/gamepanel?game=lettertycoon', players: '' },
  { name: 'Russian Railroads', url: '/gamepanel?game=russianrailroads', players: '' },
  { name: 'Poker Texas Hold\'em', url: '/gamepanel?game=texasholdem', players: '' },
  { name: 'Nine Men\'s Morris', url: '/gamepanel?game=ninemensmorris', players: '' },
  { name: 'Blackjack', url: '/gamepanel?game=blackjack', players: '' },
  { name: 'Framework', url: '/gamepanel?game=framework', players: '' },
  { name: 'Scopa', url: '/gamepanel?game=scopa', players: '' },
  { name: 'Gin Rummy', url: '/gamepanel?game=ginrummy', players: '' },
  { name: 'Roll to the Top: Journeys', url: '/gamepanel?game=rolltothetopjourneys', players: '' },
  { name: 'Spades', url: '/gamepanel?game=spades', players: '' },
  { name: 'Troyes Dice', url: '/gamepanel?game=troyesdice', players: '' },
  { name: 'Stella – Dixit Universe', url: '/gamepanel?game=stella', players: '' },
  { name: 'Tash-Kalar', url: '/gamepanel?game=tashkalar', players: '' },
  { name: 'Hardback', url: '/gamepanel?game=hardback', players: '' },
  { name: 'Hanamikoji', url: '/gamepanel?game=hanamikoji', players: '' },
  { name: 'Cardiceo', url: '/gamepanel?game=cardiceo', players: '' },
  { name: 'Farkle', url: '/gamepanel?game=farkle', players: '' },
  { name: 'Vulture Culture', url: '/gamepanel?game=vultureculture', players: '' },
  { name: 'SETUP', url: '/gamepanel?game=setup', players: '' },
  { name: 'Hugo', url: '/gamepanel?game=escapefromthehiddencastle', players: '' },
  { name: 'District Noir', url: '/gamepanel?game=throneandthegrail', players: '' },
  { name: 'Briscola', url: '/gamepanel?game=briscola', players: '' },
  { name: 'Super Fantasy Brawl', url: '/gamepanel?game=superfantasybrawl', players: '' },
  { name: 'Fruit Picking', url: '/gamepanel?game=fruitpicking', players: '' },
  { name: 'Concept', url: '/gamepanel?game=concept', players: '' },
  { name: 'Exhibition: 20th Century', url: '/gamepanel?game=exhibitiontwentiethcentury', players: '' },
  { name: 'Koryŏ', url: '/gamepanel?game=koryo', players: '' },
  { name: 'Troyes', url: '/gamepanel?game=troyes', players: '' },
  { name: 'Pocket Cats', url: '/gamepanel?game=pocketcats', players: '' },
  { name: 'Soluna', url: '/gamepanel?game=soluna', players: '' },
  { name: 'Cacao', url: '/gamepanel?game=cacao', players: '' },
  { name: 'Not Alone', url: '/gamepanel?game=notalone', players: '' },
  { name: 'Chinese checkers', url: '/gamepanel?game=chinesecheckers', players: '' },
  { name: 'Kahuna', url: '/gamepanel?game=kahuna', players: '' },
  { name: 'Tranquility: The Ascent', url: '/gamepanel?game=tranquilitytheascent', players: '' },
  { name: 'ToeShamBo', url: '/gamepanel?game=toeshambo', players: '' },
  { name: 'Sobek', url: '/gamepanel?game=sobek', players: '' },
  { name: 'Hex', url: '/gamepanel?game=hex', players: '' },
  { name: 'Takenokolor', url: '/gamepanel?game=takenokolor', players: '' },
  { name: 'Eminent Domain', url: '/gamepanel?game=eminentdomain', players: '' },
  { name: 'Teotihuacan: City of Gods', url: '/gamepanel?game=teotihuacan', players: '' },
  { name: 'Celestia', url: '/gamepanel?game=celestia', players: '' },
  { name: 'Caylus', url: '/gamepanel?game=caylus', players: '' },
  { name: 'Senet', url: '/gamepanel?game=senet', players: '' },
  { name: 'Haiclue', url: '/gamepanel?game=haiclue', players: '' },
  { name: 'Let\'s Catch the Lion!', url: '/gamepanel?game=letscatchthelion', players: '' },
  { name: 'The King\'s Guild', url: '/gamepanel?game=kingsguild', players: '' },
  { name: 'Vault: A Solitaire Dice Game', url: '/gamepanel?game=vault', players: '' },
  { name: 'Hawaii', url: '/gamepanel?game=hawaii', players: '' },
  { name: 'The Boss', url: '/gamepanel?game=theboss', players: '' },
  { name: 'Scratch and Catch', url: '/gamepanel?game=scratchandcatch', players: '' },
  { name: 'Middle Ages', url: '/gamepanel?game=middleages', players: '' },
  { name: 'President', url: '/gamepanel?game=president', players: '' },
  { name: 'Neutreeko', url: '/gamepanel?game=neutreeko', players: '' },
  { name: 'Room 25', url: '/gamepanel?game=roomtwentyfive', players: '' },
  { name: 'River Valley Glassworks', url: '/gamepanel?game=rivervalleyglassworks', players: '' },
  { name: 'Haggis', url: '/gamepanel?game=haggis', players: '' },
  { name: 'For Northwood!', url: '/gamepanel?game=fornorthwood', players: '' },
  { name: 'Now Boarding', url: '/gamepanel?game=nowboarding', players: '' },
  { name: 'Yokai', url: '/gamepanel?game=yokai', players: '' },
  { name: 'Baby Dinosaur Rescue', url: '/gamepanel?game=babydinosaurrescue', players: '' },
  { name: 'Cinco', url: '/gamepanel?game=cinco', players: '' },
  { name: 'Citadels', url: '/gamepanel?game=citadels', players: '' },
  { name: 'Number Drop', url: '/gamepanel?game=numberdrop', players: '' },
  { name: 'Tic-Tac Match', url: '/gamepanel?game=tictacmatch', players: '' },
  { name: 'Kings in the Corner', url: '/gamepanel?game=kingsinthecorner', players: '' },
  { name: 'Pylos', url: '/gamepanel?game=pylos', players: '' },
  { name: 'Orchard', url: '/gamepanel?game=orchard', players: '' },
  { name: 'Bobail', url: '/gamepanel?game=bobail', players: '' },
  { name: 'Hadara', url: '/gamepanel?game=hadara', players: '' },
  { name: '61 Autumn leaves', url: '/gamepanel?game=sixtyone', players: '' },
  { name: 'Eruption', url: '/gamepanel?game=akeruption', players: '' },
  { name: 'Quantum', url: '/gamepanel?game=quantum', players: '' },
  { name: 'Star Fluxx', url: '/gamepanel?game=starfluxx', players: '' },
  { name: 'Leaders', url: '/gamepanel?game=leaders', players: '' },
  { name: 'Legendary Inventors', url: '/gamepanel?game=inventors', players: '' },
  { name: 'Go', url: '/gamepanel?game=classicgo', players: '' },
  { name: 'Cosmoctopus', url: '/gamepanel?game=cosmoctopus', players: '' },
  { name: 'Yokohama', url: '/gamepanel?game=yokohama', players: '' },
  { name: 'Grove', url: '/gamepanel?game=grovesolitaire', players: '' },
  { name: 'Keyflower', url: '/gamepanel?game=keyflower', players: '' },
  { name: 'Open Face Chinese Poker', url: '/gamepanel?game=openfacechinesepoker', players: '' },
  { name: 'Vaalbara', url: '/gamepanel?game=vaalbara', players: '' },
  { name: 'Quantik', url: '/gamepanel?game=quantik', players: '' },
  { name: 'Welcome To New Las Vegas', url: '/gamepanel?game=welcometonewlasvegas', players: '' },
  { name: 'Whist 22', url: '/gamepanel?game=whisttwentytwo', players: '' },
  { name: 'Abra Chadabra', url: '/gamepanel?game=abrachadabra', players: '' },
  { name: 'Pax Pamir: Second Edition', url: '/gamepanel?game=paxpamir', players: '' },
  { name: 'Dingo\'s Dreams', url: '/gamepanel?game=dingosdreams', players: '' },
  { name: 'Squadro', url: '/gamepanel?game=squadro', players: '' },
  { name: 'Dog Lover', url: '/gamepanel?game=doglover', players: '' },
  { name: 'Biomos', url: '/gamepanel?game=biomos', players: '' },
  { name: 'Abalone', url: '/gamepanel?game=abalone', players: '' },
  { name: 'Siam', url: '/gamepanel?game=siam', players: '' },
  { name: 'Krosmaster Arena', url: '/gamepanel?game=krosmasterarena', players: '' },
  { name: 'Elfenland', url: '/gamepanel?game=elfenland', players: '' },
  { name: 'Knister', url: '/gamepanel?game=knister', players: '' },
  { name: 'Ultimate Railroads', url: '/gamepanel?game=ultimaterailroads', players: '' },
  { name: 'Trailblazers', url: '/gamepanel?game=trailblazers', players: '' },
  { name: 'Lewis & Clark', url: '/gamepanel?game=lewisclark', players: '' },
  { name: 'Orapa Mine', url: '/gamepanel?game=orapamine', players: '' },
  { name: 'Time Masters', url: '/gamepanel?game=timemasters', players: '' },
  { name: 'Sapiens', url: '/gamepanel?game=sapiens', players: '' },
  { name: 'Noah', url: '/gamepanel?game=noah', players: '' },
  { name: 'Paint the Roses', url: '/gamepanel?game=painttheroses', players: '' },
  { name: 'Seikatsu', url: '/gamepanel?game=seikatsu', players: '' },
  { name: 'Palace', url: '/gamepanel?game=palace', players: '' },
  { name: 'After Us', url: '/gamepanel?game=afterus', players: '' },
  { name: 'Connect6', url: '/gamepanel?game=connectsix', players: '' },
  { name: 'Tobago', url: '/gamepanel?game=tobago', players: '' },
  { name: 'The Battle for Hill 218', url: '/gamepanel?game=battleforhill', players: '' },
  { name: 'Taluva', url: '/gamepanel?game=taluva', players: '' },
  { name: 'In The Year of the Dragon', url: '/gamepanel?game=intheyearofthedragon', players: '' },
  { name: 'That\'s Life!', url: '/gamepanel?game=thatslife', players: '' },
  { name: 'Pentaquest', url: '/gamepanel?game=pentaquest', players: '' },
  { name: 'Monster Factory', url: '/gamepanel?game=monsterfactory', players: '' },
  { name: 'The Fate of the Fellowship', url: '/gamepanel?game=fateoffellowship', players: '' },
  { name: 'Euchre', url: '/gamepanel?game=euchre', players: '' },
  { name: 'Kami', url: '/gamepanel?game=kami', players: '' },
  { name: 'Kado', url: '/gamepanel?game=kado', players: '' },
  { name: 'Xiangqi', url: '/gamepanel?game=xiangqi', players: '' },
  { name: 'Pax Renaissance', url: '/gamepanel?game=paxrenaissance', players: '' },
  { name: 'Canasta', url: '/gamepanel?game=canasta', players: '' },
  { name: 'Festival', url: '/gamepanel?game=festival', players: '' },
  { name: 'Imhotep', url: '/gamepanel?game=imhotep', players: '' },
  { name: 'Roppyakken', url: '/gamepanel?game=roppyakken', players: '' },
  { name: 'Ludo', url: '/gamepanel?game=ludo', players: '' },
  { name: 'K2', url: '/gamepanel?game=k2', players: '' },
  { name: 'Ink', url: '/gamepanel?game=ink', players: '' },
  { name: 'Elawa', url: '/gamepanel?game=elawa', players: '' },
  { name: 'Trekking the World', url: '/gamepanel?game=trekkingtheworld', players: '' },
  { name: 'Boomerang: Australia', url: '/gamepanel?game=boomerangaustralia', players: '' },
  { name: 'Illustori', url: '/gamepanel?game=illustori', players: '' },
  { name: 'Wizards of the Grimoire', url: '/gamepanel?game=wizardsgrimoire', players: '' },
  { name: 'Survive The Island', url: '/gamepanel?game=survive', players: '' },
  { name: 'Pente', url: '/gamepanel?game=pente', players: '' },
  { name: 'Viva Catrina', url: '/gamepanel?game=vivacatrina', players: '' },
  { name: 'Battle Spirits Saga', url: '/gamepanel?game=battlespiritssaga', players: '' },
  { name: 'Rage', url: '/gamepanel?game=rage', players: '' },
  { name: 'Formula D', url: '/gamepanel?game=formulad', players: '' },
  { name: 'DIG UP Adventure', url: '/gamepanel?game=digupadventure', players: '' },
  { name: 'A.E.R.O.', url: '/gamepanel?game=aero', players: '' },
  { name: 'Ghost At Home', url: '/gamepanel?game=ghostathome', players: '' },
  { name: 'Look at the Stars', url: '/gamepanel?game=lookatthestars', players: '' },
  { name: 'Fairy Trails', url: '/gamepanel?game=fairytrails', players: '' },
  { name: 'Ice Cold Ice Hockey', url: '/gamepanel?game=icecoldicehockey', players: '' },
  { name: 'Automobiles', url: '/gamepanel?game=automobiles', players: '' },
  { name: 'Dicy Cards', url: '/gamepanel?game=dicycards', players: '' },
  { name: 'Perfect Words', url: '/gamepanel?game=perfectwords', players: '' },
  { name: 'Gaïa', url: '/gamepanel?game=gaia', players: '' },
  { name: 'Timeline Twist', url: '/gamepanel?game=timelinetwist', players: '' },
  { name: 'Tea Time', url: '/gamepanel?game=teatime', players: '' },
  { name: 'Off the Rails', url: '/gamepanel?game=offtherails', players: '' },
  { name: 'My First Castle Panic', url: '/gamepanel?game=myfirstcastlepanic', players: '' },
  { name: 'Farm Club', url: '/gamepanel?game=farmclub', players: '' },
  { name: 'Quibbles', url: '/gamepanel?game=quibbles', players: '' },
  { name: 'Nile', url: '/gamepanel?game=aknile', players: '' },
  { name: 'Dungeon Twister', url: '/gamepanel?game=dungeontwister', players: '' },
  { name: 'Anachrony', url: '/gamepanel?game=anachrony', players: '' },
  { name: 'Sevens', url: '/gamepanel?game=sevens', players: '' },
  { name: 'Deus', url: '/gamepanel?game=deus', players: '' },
  { name: '8 Masters\' Revenge', url: '/gamepanel?game=eightmastersrevenge', players: '' },
  { name: 'Saint Poker', url: '/gamepanel?game=saintpoker', players: '' },
  { name: 'Crazy Farmers', url: '/gamepanel?game=crazyfarmers', players: '' },
  { name: 'Diced Tomatoes', url: '/gamepanel?game=dicedtomatoes', players: '' },
  { name: 'Cubosaurs', url: '/gamepanel?game=cubosaurs', players: '' },
  { name: 'Kabaleo', url: '/gamepanel?game=kabaleo', players: '' },
  { name: 'Diceathlon', url: '/gamepanel?game=diceathlon', players: '' },
  { name: 'Caper: Europe', url: '/gamepanel?game=capereurope', players: '' },
  { name: 'Gang of Dice', url: '/gamepanel?game=gangofdice', players: '' },
  { name: 'Rumble Nation', url: '/gamepanel?game=rumblenation', players: '' },
  { name: 'Four Color Cards', url: '/gamepanel?game=fourcolorcards', players: '' },
  { name: 'Eternitium', url: '/gamepanel?game=eternitium', players: '' },
  { name: 'Evolution', url: '/gamepanel?game=evolution', players: '' },
  { name: 'Dragon Castle', url: '/gamepanel?game=dragoncastle', players: '' },
  { name: 'Praga Caput Regni', url: '/gamepanel?game=praga', players: '' },
  { name: 'Qawale', url: '/gamepanel?game=qawale', players: '' },
  { name: 'Go-Stop', url: '/gamepanel?game=gostop', players: '' },
  { name: 'Orion Duel', url: '/gamepanel?game=orionduel', players: '' },
  { name: 'Ninjan', url: '/gamepanel?game=ninjan', players: '' },
  { name: 'Metro', url: '/gamepanel?game=metro', players: '' },
  { name: 'Chocolate Factory', url: '/gamepanel?game=chocolatefactory', players: '' },
  { name: 'Dédale', url: '/gamepanel?game=dedale', players: '' },
  { name: 'Shut the Box', url: '/gamepanel?game=shutthebox', players: '' },
  { name: 'Mijnlieff', url: '/gamepanel?game=mijnlieff', players: '' },
  { name: 'Skat', url: '/gamepanel?game=skat', players: '' },
  { name: 'Forage', url: '/gamepanel?game=forage', players: '' },
  { name: 'Minhwatu', url: '/gamepanel?game=minhwatu', players: '' },
  { name: 'Mapmaker: The Gerrymandering Game', url: '/gamepanel?game=mapmaker', players: '' },
  { name: 'Secret Moon', url: '/gamepanel?game=secretmoon', players: '' },
  { name: 'Hypnosia', url: '/gamepanel?game=hypnosia', players: '' },
  { name: 'Dice Hospital: ER – Emergency Roll', url: '/gamepanel?game=dicehospitaler', players: '' },
  { name: 'Durak', url: '/gamepanel?game=durak', players: '' },
  { name: 'Liverpool (Cozy Oaks) Rummy', url: '/gamepanel?game=liverpoolrummy', players: '' },
  { name: 'Strands', url: '/gamepanel?game=strands', players: '' },
  { name: 'United Square', url: '/gamepanel?game=unitedsquare', players: '' },
  { name: 'Mythicals the boardgame', url: '/gamepanel?game=mythicalstheboardgame', players: '' },
  { name: 'Cloud City', url: '/gamepanel?game=cloudcity', players: '' },
  { name: 'Betta', url: '/gamepanel?game=betta', players: '' },
  { name: 'Poker Dice', url: '/gamepanel?game=pokerdice', players: '' },
  { name: 'Crime Zoom: A Dirty Objective', url: '/gamepanel?game=crimezoom', players: '' },
  { name: 'Spyrium', url: '/gamepanel?game=spyrium', players: '' },
  { name: 'Refuge', url: '/gamepanel?game=refuge', players: '' },
  { name: 'Unconditional Surrender! World War 2 in Europe', url: '/gamepanel?game=unconditionalsurrender', players: '' },
  { name: 'Rainbow', url: '/gamepanel?game=rainbow', players: '' },
  { name: 'None Shall Pass!', url: '/gamepanel?game=noneshallpass', players: '' },
  { name: 'Gygès', url: '/gamepanel?game=gyges', players: '' },
  { name: 'Nippon', url: '/gamepanel?game=nippon', players: '' },
  { name: 'Botanicus', url: '/gamepanel?game=botanicus', players: '' },
  { name: 'Niagara', url: '/gamepanel?game=niagara', players: '' },
  { name: 'Linx', url: '/gamepanel?game=linx', players: '' },
  { name: 'That Time You Killed Me', url: '/gamepanel?game=thattimeyoukilledme', players: '' },
  { name: 'Lords of Xidit', url: '/gamepanel?game=lox', players: '' },
  { name: 'Splitter', url: '/gamepanel?game=splitter', players: '' },
  { name: 'Balloon Pop!', url: '/gamepanel?game=balloonpop', players: '' },
  { name: 'Architects of Amytis', url: '/gamepanel?game=architectsofamytis', players: '' },
  { name: 'Hens', url: '/gamepanel?game=hens', players: '' },
  { name: 'Logger', url: '/gamepanel?game=logger', players: '' },
  { name: 'Trellis', url: '/gamepanel?game=trellis', players: '' },
  { name: 'Go Fish', url: '/gamepanel?game=gofish', players: '' },
  { name: 'Hoarders', url: '/gamepanel?game=hoarders', players: '' },
  { name: 'Zuuli', url: '/gamepanel?game=zuuli', players: '' },
  { name: 'Expeditions: Around the World', url: '/gamepanel?game=expeditions', players: '' },
  { name: 'Cat Café', url: '/gamepanel?game=catcafe', players: '' },
  { name: 'Go Goa', url: '/gamepanel?game=gogoa', players: '' },
  { name: 'Alveole', url: '/gamepanel?game=alveole', players: '' },
  { name: 'The Wolves', url: '/gamepanel?game=thewolves', players: '' },
  { name: 'The Shipwreck Arcana', url: '/gamepanel?game=theshipwreckarcana', players: '' },
  { name: 'Umbrella', url: '/gamepanel?game=umbrella', players: '' },
  { name: 'Sherlock 13', url: '/gamepanel?game=sherlockthirteen', players: '' },
  { name: 'DVONN', url: '/gamepanel?game=dvonn', players: '' },
  { name: 'Mammalath', url: '/gamepanel?game=mammalath', players: '' },
  { name: '31', url: '/gamepanel?game=thirtyone', players: '' },
  { name: 'El Grande', url: '/gamepanel?game=elgrande', players: '' },
  { name: 'The Palaces of Carrara', url: '/gamepanel?game=carrara', players: '' },
  { name: 'Dinosaur Tea Party', url: '/gamepanel?game=dinosaurteaparty', players: '' },
  { name: 'Nautilus', url: '/gamepanel?game=nautilus', players: '' },
  { name: 'Booty Dice', url: '/gamepanel?game=bootydice', players: '' },
  { name: 'On Tour', url: '/gamepanel?game=ontour', players: '' },
  { name: 'Dobble Connect', url: '/gamepanel?game=dobbleconnect', players: '' },
  { name: 'Panic Lab', url: '/gamepanel?game=paniclab', players: '' },
  { name: 'Ginkgopolis', url: '/gamepanel?game=ginkgopolis', players: '' },
  { name: 'Lure', url: '/gamepanel?game=lure', players: '' },
  { name: 'Ponte del Diavolo', url: '/gamepanel?game=pontedeldiavolo', players: '' },
  { name: 'Jurassic Snack', url: '/gamepanel?game=jurassicsnack', players: '' },
  { name: 'Solar Storm', url: '/gamepanel?game=solarstorm', players: '' },
  { name: 'Boomerang: Europe', url: '/gamepanel?game=boomerangeurope', players: '' },
  { name: 'Tournay', url: '/gamepanel?game=tournay', players: '' },
  { name: 'Dots and Boxes', url: '/gamepanel?game=dotsandboxes', players: '' },
  { name: 'Rolling Pins', url: '/gamepanel?game=rollingpins', players: '' },
  { name: 'Diam\'s', url: '/gamepanel?game=diams', players: '' },
  { name: 'Pugs in Mugs', url: '/gamepanel?game=pugsinmugs', players: '' },
  { name: 'Mega Jackpot', url: '/gamepanel?game=megajackpot', players: '' },
  { name: 'Yaxha', url: '/gamepanel?game=yaxha', players: '' },
  { name: 'Circle of Life', url: '/gamepanel?game=circleoflife', players: '' },
  { name: '101: the match', url: '/gamepanel?game=oneohone', players: '' },
  { name: 'Boreal', url: '/gamepanel?game=boreal', players: '' },
  { name: 'China Gold', url: '/gamepanel?game=chinagold', players: '' },
  { name: 'Signorie', url: '/gamepanel?game=signorie', players: '' },
  { name: '24/7: The Game', url: '/gamepanel?game=twentyfourseven', players: '' },
  { name: 'Blooms', url: '/gamepanel?game=blooms', players: '' },
  { name: 'Space Empires: 4X', url: '/gamepanel?game=spaceempires', players: '' },
  { name: 'Origin', url: '/gamepanel?game=origin', players: '' },
  { name: 'Flip Freighters', url: '/gamepanel?game=flipfreighters', players: '' },
  { name: 'Zooloretto', url: '/gamepanel?game=zooloretto', players: '' },
  { name: 'Captain Tsubasa: The card game', url: '/gamepanel?game=campeones', players: '' },
  { name: 'Geek Out! Masters', url: '/gamepanel?game=geekoutmasters', players: '' },
  { name: 'Almadi', url: '/gamepanel?game=almadi', players: '' },
  { name: 'Crusaders: Thy Will Be Done', url: '/gamepanel?game=crusadersthywillbedone', players: '' },
  { name: 'Oh-Seven', url: '/gamepanel?game=ohseven', players: '' },
  { name: 'City of the Big Shoulders', url: '/gamepanel?game=cityofthebigshoulders', players: '' },
  { name: 'Junk Drawer', url: '/gamepanel?game=junkdrawer', players: '' },
  { name: 'Rallyman: DIRT', url: '/gamepanel?game=rallymandirt', players: '' },
  { name: 'Zefiria', url: '/gamepanel?game=zefiria', players: '' },
  { name: 'Outlaws: Last Man Standing', url: '/gamepanel?game=outlaws', players: '' },
  { name: 'Linkage', url: '/gamepanel?game=linkage', players: '' },
  { name: 'Armadöra', url: '/gamepanel?game=armadora', players: '' },
  { name: 'Bug', url: '/gamepanel?game=bug', players: '' },
  { name: 'Metromania', url: '/gamepanel?game=metromaniab', players: '' },
  { name: 'Caravan', url: '/gamepanel?game=caravan', players: '' },
  { name: '7 Wonders Dice', url: '/gamepanel?game=sevenwondersdice', players: '' },
  { name: 'DinoGenics', url: '/gamepanel?game=dinogenics', players: '' },
  { name: 'Dodo', url: '/gamepanel?game=dodo', players: '' },
  { name: 'Polis: Fight for Hegemony', url: '/gamepanel?game=polis', players: '' },
  { name: 'Boss Quest', url: '/gamepanel?game=bossquest', players: '' },
  { name: 'Bloxo', url: '/gamepanel?game=caboodle', players: '' },
  { name: 'Diced Veggies', url: '/gamepanel?game=dicedveggies', players: '' },
  { name: 'Dungeon Petz', url: '/gamepanel?game=dungeonpetz', players: '' },
  { name: 'Uptown', url: '/gamepanel?game=uptown', players: '' },
  { name: 'Barbu', url: '/gamepanel?game=barbu', players: '' },
  { name: 'Expedition: Northwest Passage', url: '/gamepanel?game=northwestpassage', players: '' },
  { name: 'Ratjack', url: '/gamepanel?game=ratjack', players: '' },
  { name: 'Hidden Leaders', url: '/gamepanel?game=hiddenleaders', players: '' },
  { name: 'A Gest of Robin Hood', url: '/gamepanel?game=agestofrobinhood', players: '' },
  { name: 'GrumbleStone', url: '/gamepanel?game=grumblestone', players: '' },
  { name: 'Yaniv', url: '/gamepanel?game=yaniv', players: '' },
  { name: 'Arctic Scavengers', url: '/gamepanel?game=arcticscavengers', players: '' },
  { name: 'Kulami', url: '/gamepanel?game=kulami', players: '' },
  { name: 'Gatsby', url: '/gamepanel?game=gatsby', players: '' },
  { name: 'Takara Island', url: '/gamepanel?game=takaraisland', players: '' },
  { name: 'Le Roy des Ribauds', url: '/gamepanel?game=leroydesribauds', players: '' },
  { name: 'Quetzal', url: '/gamepanel?game=quetzal', players: '' },
  { name: 'Road to 300', url: '/gamepanel?game=roadtothreehoundred', players: '' },
  { name: 'Small Islands', url: '/gamepanel?game=smallislands', players: '' },
  { name: 'Finca', url: '/gamepanel?game=finca', players: '' },
  { name: 'SteamRollers', url: '/gamepanel?game=steamrollers', players: '' },
  { name: 'Gnome Hollow', url: '/gamepanel?game=gnomehollow', players: '' },
  { name: 'Art Decko', url: '/gamepanel?game=artdecko', players: '' },
  { name: 'The Number', url: '/gamepanel?game=thenumber', players: '' },
  { name: 'Veggie Garden', url: '/gamepanel?game=veggiegarden', players: '' },
  { name: 'Soulaween', url: '/gamepanel?game=soulaween', players: '' },
  { name: 'Paper World', url: '/gamepanel?game=paperworld', players: '' },
  { name: 'Ultimate Tic-Tac-Toe', url: '/gamepanel?game=ultimatetictactoe', players: '' },
  { name: 'Sheep Boom Bah', url: '/gamepanel?game=sheepboombah', players: '' },
  { name: 'Art Thief', url: '/gamepanel?game=artthief', players: '' },
  { name: 'Bandada', url: '/gamepanel?game=bandada', players: '' },
  { name: 'Sail', url: '/gamepanel?game=sail', players: '' },
  { name: 'Nanga Parbat', url: '/gamepanel?game=nangaparbat', players: '' },
  { name: 'Panda Spin', url: '/gamepanel?game=pandaspin', players: '' },
  { name: 'Dobro', url: '/gamepanel?game=dobro', players: '' },
  { name: 'Uncle Chestnut\'s Table Gype', url: '/gamepanel?game=unclechestnuttablegype', players: '' },
  { name: 'TacTile', url: '/gamepanel?game=tactile', players: '' },
  { name: 'Choconnect', url: '/gamepanel?game=choconnect', players: '' },
  { name: 'Dice Pyramid', url: '/gamepanel?game=dicepyramid', players: '' },
  { name: 'VektoRace', url: '/gamepanel?game=vektorace', players: '' },
  { name: 'Tang Hu Lu', url: '/gamepanel?game=tanghulu', players: '' },
  { name: 'Exit Strategy', url: '/gamepanel?game=exitstrategy', players: '' },
  { name: '51st State', url: '/gamepanel?game=fiftyfirststate', players: '' },
  { name: 'Trike', url: '/gamepanel?game=trike', players: '' },
  { name: 'Big Two', url: '/gamepanel?game=bigtwo', players: '' },
  { name: 'The way to Juliet', url: '/gamepanel?game=thewaytojuliet', players: '' },
  { name: 'Penalty Challenge', url: '/gamepanel?game=penaltychallenge', players: '' },
  { name: 'Tiny Epic Defenders (Second Edition)', url: '/gamepanel?game=tinyepicdefenders', players: '' },
  { name: 'Madeira', url: '/gamepanel?game=madeira', players: '' },
  { name: 'Dark Agent', url: '/gamepanel?game=darkagent', players: '' },
  { name: 'Gangsta!', url: '/gamepanel?game=gangsta', players: '' },
  { name: 'Quartermaster General: East Front', url: '/gamepanel?game=quartermastergeneraleastfront', players: '' },
  { name: 'The Brambles', url: '/gamepanel?game=thebrambles', players: '' },
  { name: 'Stalk Exchange', url: '/gamepanel?game=stalkexchange', players: '' },
  { name: 'Amyitis', url: '/gamepanel?game=amyitis', players: '' },
  { name: 'Mascarade', url: '/gamepanel?game=mascarade', players: '' },
  { name: 'Dinner In Paris', url: '/gamepanel?game=dinnerinparis', players: '' },
  { name: 'Paris Connection', url: '/gamepanel?game=parisconnection', players: '' },
  { name: 'Twin Tin Bots', url: '/gamepanel?game=twintinbots', players: '' },
  { name: 'Commander Chess', url: '/gamepanel?game=commanderchess', players: '' },
  { name: 'Guildes', url: '/gamepanel?game=guildes', players: '' },
  { name: 'Twinkle Twinkle', url: '/gamepanel?game=twinkletwinkle', players: '' },
  { name: 'Gopher', url: '/gamepanel?game=gopher', players: '' },
  { name: 'Pyramido: Forgotten Treasures', url: '/gamepanel?game=pyramidoft', players: '' },
  { name: 'Lines of Action', url: '/gamepanel?game=linesofaction', players: '' },
  { name: 'Good Cop Bad Cop', url: '/gamepanel?game=goodcopbadcop', players: '' },
  { name: 'Worldwide Tennis', url: '/gamepanel?game=worldwidetennis', players: '' },
  { name: 'Pyrga', url: '/gamepanel?game=pyrgos', players: '' },
  { name: 'Narabi', url: '/gamepanel?game=narabi', players: '' },
  { name: 'Lorenzo il Magnifico', url: '/gamepanel?game=lorenzo', players: '' },
  { name: 'Tikal', url: '/gamepanel?game=tikal', players: '' },
  { name: 'Simplicity', url: '/gamepanel?game=simplicity', players: '' },
  { name: 'Bao la Kiswahili', url: '/gamepanel?game=baolakiswahili', players: '' },
  { name: 'Homeworlds', url: '/gamepanel?game=homeworlds', players: '' },
  { name: 'Mia', url: '/gamepanel?game=mia', players: '' },
  { name: 'Pond', url: '/gamepanel?game=pond', players: '' },
  { name: 'Regidice', url: '/gamepanel?game=regidice', players: '' },
  { name: 'Crazy Eights', url: '/gamepanel?game=crazyeights', players: '' },
  { name: 'Get the MacGuffin', url: '/gamepanel?game=getthemacguffin', players: '' },
  { name: 'Big Time Soccer', url: '/gamepanel?game=bigtimesoccer', players: '' },
  { name: 'Ekko', url: '/gamepanel?game=ekko', players: '' },
  { name: 'Don\'t Go In There', url: '/gamepanel?game=dontgointhere', players: '' },
  { name: 'Tablut', url: '/gamepanel?game=tablut', players: '' },
  { name: 'Streets', url: '/gamepanel?game=streets', players: '' },
  { name: 'Spirits of the Forest', url: '/gamepanel?game=spiritsoftheforest', players: '' },
  { name: 'The Jelly Monster Lab', url: '/gamepanel?game=thejellymonsterlab', players: '' },
  { name: 'Cosmos: Empires', url: '/gamepanel?game=cosmosempires', players: '' },
  { name: 'Don\'t Let It Die', url: '/gamepanel?game=dontletitdie', players: '' },
  { name: 'Sensei', url: '/gamepanel?game=sensei', players: '' },
  { name: 'The Bloody Inn', url: '/gamepanel?game=bloodyinn', players: '' },
  { name: 'Bombay', url: '/gamepanel?game=bombay', players: '' },
  { name: 'Klaverjassen', url: '/gamepanel?game=klaverjassen', players: '' },
  { name: 'Herd', url: '/gamepanel?game=herd', players: '' },
  { name: 'A Fistful of Gold', url: '/gamepanel?game=fistfulofgold', players: '' },
  { name: 'Nain Jaune', url: '/gamepanel?game=nainjaune', players: '' },
  { name: 'Cairo Corridor', url: '/gamepanel?game=cairocorridor', players: '' },
  { name: 'Wizards Cup', url: '/gamepanel?game=wizardscup', players: '' },
  { name: 'Shogi', url: '/gamepanel?game=shogi', players: '' },
  { name: 'Assyria', url: '/gamepanel?game=assyria', players: '' },
  { name: 'Mind MGMT', url: '/gamepanel?game=mindmgmt', players: '' },
  { name: 'Blue Skies', url: '/gamepanel?game=blueskies', players: '' },
  { name: 'Lielow', url: '/gamepanel?game=lielow', players: '' },
  { name: 'Cucumber', url: '/gamepanel?game=cucumber', players: '' },
  { name: 'Yokai Septet', url: '/gamepanel?game=yokaiseptet', players: '' },
  { name: 'Ice and the Sky', url: '/gamepanel?game=iceandthesky', players: '' },
  { name: 'Legions', url: '/gamepanel?game=legions', players: '' },
  { name: 'Chemical Overload', url: '/gamepanel?game=chemicaloverload', players: '' },
  { name: 'Matchstick Tycoon', url: '/gamepanel?game=matchsticktycoon', players: '' },
  { name: 'GORami', url: '/gamepanel?game=gorami', players: '' },
  { name: 'Homesteaders', url: '/gamepanel?game=homesteaders', players: '' },
  { name: 'OASIS New Hope', url: '/gamepanel?game=oasis', players: '' },
  { name: 'ECK', url: '/gamepanel?game=eck', players: '' },
  { name: '99 (trick-taking card game)', url: '/gamepanel?game=ninetynine', players: '' },
  { name: 'SUPER', url: '/gamepanel?game=super', players: '' },
  { name: 'Roll Into Town', url: '/gamepanel?game=rollintotown', players: '' },
  { name: 'Veletas', url: '/gamepanel?game=veletas', players: '' },
  { name: 'Florenza: The Card Game', url: '/gamepanel?game=florenzacardgame', players: '' },
  { name: 'Claim', url: '/gamepanel?game=claim', players: '' },
  { name: 'Gold West', url: '/gamepanel?game=goldwest', players: '' },
  { name: 'Icebreaker', url: '/gamepanel?game=icebreaker', players: '' },
  { name: 'Fractal', url: '/gamepanel?game=fractal', players: '' },
  { name: 'Age of Champagne', url: '/gamepanel?game=ageofchampagne', players: '' },
  { name: 'Ticket Gagnant', url: '/gamepanel?game=ticketgagnant', players: '' },
  { name: 'Schnapsen', url: '/gamepanel?game=schnapsen', players: '' },
  { name: 'The Lady and the Tiger (Doors)', url: '/gamepanel?game=ladyandthetiger', players: '' },
  { name: 'Kmakici Family\'s greatest teatime', url: '/gamepanel?game=kmakici', players: '' },
  { name: 'Micro Dojo', url: '/gamepanel?game=microdojo', players: '' },
  { name: 'Seotda', url: '/gamepanel?game=seotda', players: '' },
  { name: 'Astra', url: '/gamepanel?game=astra', players: '' },
  { name: 'Once Upon A Forest', url: '/gamepanel?game=onceuponaforest', players: '' },
  { name: 'Dou Dizhu', url: '/gamepanel?game=fightthelandlord', players: '' },
  { name: 'Hoola', url: '/gamepanel?game=hoola', players: '' },
  { name: 'Dice Summoners', url: '/gamepanel?game=dicesummoners', players: '' },
  { name: 'Qango', url: '/gamepanel?game=qango', players: '' },
  { name: 'Castles of Caleira', url: '/gamepanel?game=castlesofcaleira', players: '' },
  { name: 'Tiny Farms', url: '/gamepanel?game=tinyfarms', players: '' },
  { name: 'Verona Twist', url: '/gamepanel?game=veronatwist', players: '' },
  { name: 'Rolled West', url: '/gamepanel?game=rolledwest', players: '' },
  { name: 'Khiva', url: '/gamepanel?game=khiva', players: '' },
  { name: 'Hack Trick', url: '/gamepanel?game=hacktrick', players: '' },
  { name: 'Cookie Addict!', url: '/gamepanel?game=cookieaddict', players: '' },
  { name: 'Gift of Tulips', url: '/gamepanel?game=giftoftulips', players: '' },
  { name: 'Mythic Battles: Ragnarök', url: '/gamepanel?game=mythicbattlesragnarok', players: '' },
  { name: 'Legend Raiders', url: '/gamepanel?game=legendraiders', players: '' },
  { name: 'Draft Cider', url: '/gamepanel?game=draftcider', players: '' },
  { name: 'Dragon Keeper: The Dungeon', url: '/gamepanel?game=dragonkeeper', players: '' },
  { name: 'Tumbleweed', url: '/gamepanel?game=tumbleweed', players: '' },
  { name: 'Las Vegan', url: '/gamepanel?game=lasvegan', players: '' },
  { name: 'Hungarian Tarokk', url: '/gamepanel?game=hungariantarokk', players: '' },
  { name: 'Kingscraft', url: '/gamepanel?game=kingscraft', players: '' },
  { name: 'Giraffe Raffe', url: '/gamepanel?game=girafferaffe', players: '' },
  { name: 'Krosmaster Blast', url: '/gamepanel?game=krosmasterblast', players: '' },
  { name: 'Penny Press', url: '/gamepanel?game=pennypress', players: '' },
  { name: 'Marram', url: '/gamepanel?game=marram', players: '' },
  { name: 'Meridians', url: '/gamepanel?game=meridians', players: '' },
  { name: 'Garden Nation', url: '/gamepanel?game=gardennation', players: '' },
  { name: 'Herrlof', url: '/gamepanel?game=herrlof', players: '' },
  { name: 'Gear & Piston', url: '/gamepanel?game=gearnpiston', players: '' },
  { name: 'Yin Yang', url: '/gamepanel?game=yinyang', players: '' },
  { name: 'Robots Ate Our Pizza', url: '/gamepanel?game=robotsateourpizza', players: '' },
  { name: 'Dragon Line', url: '/gamepanel?game=dragonline', players: '' },
  { name: 'Cóatl', url: '/gamepanel?game=coatl', players: '' },
  { name: 'Eriantys', url: '/gamepanel?game=eriantys', players: '' },
  { name: 'Oust', url: '/gamepanel?game=oust', players: '' },
  { name: 'Caïrn', url: '/gamepanel?game=cairn', players: '' },
  { name: 'Four Gardens', url: '/gamepanel?game=fourgardens', players: '' },
  { name: 'Kiri-ai: The Duel', url: '/gamepanel?game=kiriaitheduel', players: '' },
  { name: 'ONE', url: '/gamepanel?game=one', players: '' },
  { name: 'Hadron', url: '/gamepanel?game=hadron', players: '' },
  { name: 'Kokeshi', url: '/gamepanel?game=kokeshi', players: '' },
  { name: 'Inverted Dice', url: '/gamepanel?game=inverteddice', players: '' },
  { name: 'Chicago Express', url: '/gamepanel?game=chicagoexpress', players: '' },
  { name: 'Lifeline', url: '/gamepanel?game=lifeline', players: '' },
  { name: 'Hey, That\'s My Fish!', url: '/gamepanel?game=heythatsmyfish', players: '' },
  { name: 'Deliverance', url: '/gamepanel?game=deliverance', players: '' },
  { name: 'Moonlight: The Land of the Wolves', url: '/gamepanel?game=moonlight', players: '' },
  { name: 'Hawaiian Hanafuda', url: '/gamepanel?game=sakura', players: '' },
  { name: 'Lady\'s Choice', url: '/gamepanel?game=ladyschoice', players: '' },
  { name: 'NXS', url: '/gamepanel?game=nxs', players: '' },
  { name: 'Crisps!', url: '/gamepanel?game=crisps', players: '' },
  { name: 'Silo', url: '/gamepanel?game=silo', players: '' },
  { name: 'Hydroracers', url: '/gamepanel?game=hydroracers', players: '' },
  { name: 'Mod Ten', url: '/gamepanel?game=modten', players: '' },
  { name: 'Isaac', url: '/gamepanel?game=isaac', players: '' },
  { name: 'Quinque', url: '/gamepanel?game=quinque', players: '' },
  { name: 'Pili Pili', url: '/gamepanel?game=pilipili', players: '' },
  { name: 'Cake Master', url: '/gamepanel?game=cakemaster', players: '' },
  { name: 'Mystling Academy', url: '/gamepanel?game=mystlingacademy', players: '' },
  { name: 'Lost Explorers', url: '/gamepanel?game=lostexplorers', players: '' },
  { name: 'The Yellow House', url: '/gamepanel?game=theyellowhouse', players: '' },
  { name: 'Ahoy', url: '/gamepanel?game=ahoy', players: '' },
  { name: 'Vegetable Stock', url: '/gamepanel?game=vegetablestock', players: '' },
  { name: 'Mattock', url: '/gamepanel?game=mattock', players: '' },
  { name: 'Mutant Crops', url: '/gamepanel?game=mutantcrops', players: '' },
  { name: 'Zener', url: '/gamepanel?game=zener', players: '' },
  { name: 'Dungeon Rummy', url: '/gamepanel?game=dungeonrummy', players: '' },
  { name: 'Drones vs Seagulls', url: '/gamepanel?game=dronesvsseagulls', players: '' },
  { name: 'Nacho Pile', url: '/gamepanel?game=nachopile', players: '' },
  { name: 'Turncoats', url: '/gamepanel?game=turncoats', players: '' },
  { name: 'Coupell', url: '/gamepanel?game=coupell', players: '' },
  { name: 'Solo Whist', url: '/gamepanel?game=solowhist', players: '' },
  { name: 'Murus Gallicus', url: '/gamepanel?game=murusgallicus', players: '' },
  { name: 'Dewan', url: '/gamepanel?game=dewan', players: '' },
  { name: 'Pier 18', url: '/gamepanel?game=piereighteen', players: '' },
  { name: 'The Game Makers', url: '/gamepanel?game=thegamemakers', players: '' },
  { name: 'Steam Works', url: '/gamepanel?game=steamworks', players: '' },
  { name: 'Talon', url: '/gamepanel?game=talon', players: '' },
  { name: 'Masters of Renaissance: Lorenzo il Magnifico - The Card Game', url: '/gamepanel?game=mastersofrenaissance', players: '' },
  { name: 'Egocentric World', url: '/gamepanel?game=egocentricworld', players: '' },
  { name: 'Bids', url: '/gamepanel?game=bids', players: '' },
  { name: 'Fika', url: '/gamepanel?game=fika', players: '' },
  { name: 'The Ruhr: A Story of Coal Trade', url: '/gamepanel?game=ruhr', players: '' },
  { name: 'Khronos', url: '/gamepanel?game=khronos', players: '' },
  { name: 'Twin Palms', url: '/gamepanel?game=twinpalms', players: '' },
  { name: 'Eminent Domain: Microcosm', url: '/gamepanel?game=emdomicrocosm', players: '' },
  { name: 'Knockout Whist', url: '/gamepanel?game=knockoutwhist', players: '' },
  { name: 'Jump Gate', url: '/gamepanel?game=jumpgate', players: '' },
  { name: 'Forks: 2nd Edition', url: '/gamepanel?game=forks', players: '' },
  { name: 'YINSH', url: '/gamepanel?game=yinsh', players: '' },
  { name: 'Propuh', url: '/gamepanel?game=propuh', players: '' },
  { name: 'Grand Bazaar', url: '/gamepanel?game=grandbazaar', players: '' },
  { name: 'Vidrasso', url: '/gamepanel?game=vidrasso', players: '' },
  { name: 'Crypt', url: '/gamepanel?game=crypt', players: '' },
  { name: 'Canosa', url: '/gamepanel?game=canosa', players: '' },
  { name: '15 Days', url: '/gamepanel?game=fifteendays', players: '' },
  { name: '3000 Scoundrels', url: '/gamepanel?game=threethousandscoundrels', players: '' },
  { name: 'Roll Through the Ages: The Bronze Age', url: '/gamepanel?game=rollthroughtheagesthebronzeage', players: '' },
  { name: 'Tuned', url: '/gamepanel?game=tuned', players: '' },
  { name: 'Trusis', url: '/gamepanel?game=trusis', players: '' },
  { name: 'Capybara\'n\'Capybara', url: '/gamepanel?game=capybarancapybara', players: '' },
  { name: 'Cephalopod', url: '/gamepanel?game=cephalopod', players: '' },
  { name: 'Tiny Turbo Cars', url: '/gamepanel?game=tinyturbocars', players: '' },
  { name: 'Tsukuru Ten Ten', url: '/gamepanel?game=tsukurutenten', players: '' },
  { name: 'Shogun', url: '/gamepanel?game=shogun', players: '' },
  { name: 'Five Three Five', url: '/gamepanel?game=fivethreefive', players: '' },
  { name: 'EpiZodiak', url: '/gamepanel?game=epizodiak', players: '' },
  { name: 'Mind Cycling', url: '/gamepanel?game=mindcycling', players: '' },
  { name: 'Azure', url: '/gamepanel?game=azure', players: '' },
  { name: 'Memory', url: '/gamepanel?game=memory', players: '' },
  { name: 'Resolve', url: '/gamepanel?game=resolve', players: '' },
  { name: 'Cucco', url: '/gamepanel?game=cucco', players: '' },
  { name: 'Thrive', url: '/gamepanel?game=thrive', players: '' },
  { name: 'Envelopes of Cash', url: '/gamepanel?game=envelopesofcash', players: '' },
  { name: 'Diablo', url: '/gamepanel?game=diablo', players: '' },
  { name: 'Flume', url: '/gamepanel?game=flume', players: '' },
  { name: 'Unrest', url: '/gamepanel?game=unrest', players: '' },
  { name: 'Zola', url: '/gamepanel?game=zola', players: '' },
  { name: 'VEGEtables', url: '/gamepanel?game=vegetables', players: '' },
  { name: 'Tacta', url: '/gamepanel?game=tacta', players: '' },
  { name: 'Dragon Bridge', url: '/gamepanel?game=dragonbridge', players: '' },
  { name: 'Expressions', url: '/gamepanel?game=expressions', players: '' },
  { name: 'Nibble', url: '/gamepanel?game=nibble', players: '' },
  { name: 'Altay: Dawn of Civilization', url: '/gamepanel?game=altay', players: '' },
  { name: 'Bahama Taxi', url: '/gamepanel?game=bahamataxi', players: '' },
  { name: 'Exploration: Warzone', url: '/gamepanel?game=explorationwarzone', players: '' },
  { name: 'Vault: A Den of Thieves', url: '/gamepanel?game=vaultdenofthieves', players: '' },
  { name: 'Nature', url: '/gamepanel?game=nature', players: '' },
  { name: 'Le Dernier Peuple', url: '/gamepanel?game=ledernierpeuple', players: '' },
  { name: 'Crazy Corgi', url: '/gamepanel?game=crazycorgi', players: '' },
  { name: 'Cradle to Grave', url: '/gamepanel?game=cradletograve', players: '' },
  { name: 'Bunny Boom', url: '/gamepanel?game=bunnyboom', players: '' },
  { name: 'Chimera Station', url: '/gamepanel?game=chimerastation', players: '' },
  { name: 'Kraken Up', url: '/gamepanel?game=krakenup', players: '' },
  { name: 'Trick of the Rails', url: '/gamepanel?game=trickoftherails', players: '' },
  { name: 'Pook', url: '/gamepanel?game=pook', players: '' },
  { name: 'Medu', url: '/gamepanel?game=medu', players: '' },
  { name: 'Detective Poker', url: '/gamepanel?game=detectivepoker', players: '' },
  { name: 'Cathood', url: '/gamepanel?game=cathood', players: '' },
  { name: '420', url: '/gamepanel?game=fourtwenty', players: '' },
  { name: 'The Great American Fox Hunt', url: '/gamepanel?game=thegreatamericanfoxhunt', players: '' },
  { name: 'Zookeepers', url: '/gamepanel?game=zookeepers', players: '' },
  { name: 'Splash Down', url: '/gamepanel?game=splashdown', players: '' },
  { name: 'Streetcar', url: '/gamepanel?game=streetcar', players: '' },
  { name: 'Pinochle', url: '/gamepanel?game=pinochle', players: '' },
  { name: 'Sparts', url: '/gamepanel?game=sparts', players: '' },
  { name: 'TEKKEN - the Board Game', url: '/gamepanel?game=tekken', players: '' },
  { name: 'Medo', url: '/gamepanel?game=meadow', players: '' },
  { name: 'King of the Pitch', url: '/gamepanel?game=kingofthepitch', players: '' },
  { name: 'Japanese (Riichi) Mahjong', url: '/gamepanel?game=riichimahjong', players: '' },
  { name: 'Ti?n L�n', url: '/gamepanel?game=tienlen', players: '' },
  { name: 'Greasy Spoon', url: '/gamepanel?game=greasyspoon', players: '' },
  { name: 'Écarté', url: '/gamepanel?game=ecarte', players: '' },
  { name: 'Power Vacuum', url: '/gamepanel?game=powervacuum', players: '' },
  { name: 'Coin Age', url: '/gamepanel?game=coinage', players: '' },
  { name: 'Djambi', url: '/gamepanel?game=djambi', players: '' },
  { name: 'Fai-fo', url: '/gamepanel?game=faifo', players: '' },
  { name: 'Indian Chief', url: '/gamepanel?game=indianchief', players: '' },
  { name: 'Lepidoptery', url: '/gamepanel?game=lepidoptery', players: '' },
  { name: 'Rive', url: '/gamepanel?game=rive', players: '' },
  { name: 'Evo: The "Game no Name"', url: '/gamepanel?game=evogamenoname', players: '' },
  { name: 'Panda Rei', url: '/gamepanel?game=pandaarei', players: '' },
  { name: 'Belladone Bluff', url: '/gamepanel?game=belladonebluff', players: '' },
  { name: 'Remember When', url: '/gamepanel?game=rememberwhen', players: '' },
  { name: 'Konane', url: '/gamepanel?game=konane', players: '' },
  { name: 'Humanity', url: '/gamepanel?game=humanity', players: '' },
  { name: 'Mighty', url: '/gamepanel?game=mighty', players: '' },
  { name: 'Quartz: The Dice Game', url: '/gamepanel?game=quartzdice', players: '' },
  { name: 'Odicey', url: '/gamepanel?game=odicey', players: '' },
  { name: 'Carnuta', url: '/gamepanel?game=carnuta', players: '' },
  { name: 'Queen of Scots', url: '/gamepanel?game=queenofscots', players: '' },
  { name: 'For-Ex', url: '/gamepanel?game=forex', players: '' },
  { name: 'Coffee', url: '/gamepanel?game=coffee', players: '' },
  { name: 'Cheez-Tricks', url: '/gamepanel?game=cheeztricks', players: '' },
  { name: 'EVL', url: '/gamepanel?game=evl', players: '' },
  { name: 'Senshi', url: '/gamepanel?game=senshi', players: '' },
  { name: 'Wolf and Sheep', url: '/gamepanel?game=wolfandsheeps', players: '' },
  { name: 'Pescado Novo', url: '/gamepanel?game=pescadonovo', players: '' },
  { name: 'Tortuga 1667', url: '/gamepanel?game=tortugasixteensixtyseven', players: '' },
  { name: 'Finity', url: '/gamepanel?game=finity', players: '' },
  { name: 'Movers & Shakers', url: '/gamepanel?game=moversandshakers', players: '' },
  { name: '15 Jours en France', url: '/gamepanel?game=quinzejoursenfrance', players: '' },
  { name: 'Okanagan: Valley of the Lakes', url: '/gamepanel?game=okanagan', players: '' },
  { name: 'Rift Valley Reserve', url: '/gamepanel?game=riftvalleyreserve', players: '' },
  { name: 'Sfynx', url: '/gamepanel?game=sfynx', players: '' },
  { name: 'Qu4to', url: '/gamepanel?game=quato', players: '' },
  { name: 'Nylon-ppong', url: '/gamepanel?game=nylonppong', players: '' },
  { name: 'Spring Cleaning', url: '/gamepanel?game=springcleaning', players: '' },
  { name: 'Empire Plateau', url: '/gamepanel?game=empireplateau', players: '' },
  { name: 'Elongo', url: '/gamepanel?game=elongo', players: '' },
  { name: 'Tapas', url: '/gamepanel?game=tapas', players: '' },
  { name: 'Bower', url: '/gamepanel?game=bower', players: '' },
  { name: 'Park Life', url: '/gamepanel?game=parklife', players: '' },
  { name: 'Gems of Iridescia', url: '/gamepanel?game=gemsofiridescia', players: '' },
  { name: 'Herooj', url: '/gamepanel?game=herooj', players: '' },
  { name: 'Goblin Hood', url: '/gamepanel?game=goblinhood', players: '' },
  { name: 'The Last', url: '/gamepanel?game=thelast', players: '' },
  { name: 'Asteria', url: '/gamepanel?game=asteria', players: '' },
  { name: 'Toepen', url: '/gamepanel?game=toepen', players: '' },
  { name: 'Quirky Quarks', url: '/gamepanel?game=quirkyquarks', players: '' },
  { name: 'Run Buster', url: '/gamepanel?game=runbuster', players: '' },
  { name: 'Wastelandia', url: '/gamepanel?game=wastelandia', players: '' },
  { name: 'Festi\'vibes', url: '/gamepanel?game=festivibes', players: '' },
  { name: 'Heckin Hounds', url: '/gamepanel?game=heckinhounds', players: '' },
  { name: 'Xxung', url: '/gamepanel?game=xxung', players: '' },
  { name: 'EKONOS', url: '/gamepanel?game=ekonos', players: '' },
  { name: 'Classified Information', url: '/gamepanel?game=classifiedinformation', players: '' },
  { name: 'AVES', url: '/gamepanel?game=aves', players: '' },
  { name: 'Irish Gauge', url: '/gamepanel?game=irishgauge', players: '' },
  { name: 'Quattuor Reges', url: '/gamepanel?game=quattuorreges', players: '' },
  { name: 'Maatatahay', url: '/gamepanel?game=maatatahay', players: '' },
  { name: 'Biyi', url: '/gamepanel?game=biyi', players: '' },
  { name: 'Churn', url: '/gamepanel?game=churn', players: '' },
  { name: 'Bacon', url: '/gamepanel?game=bacon', players: '' },
  { name: 'iye', url: '/gamepanel?game=iye', players: '' },
  { name: 'Contract Bridge', url: '/gamepanel?game=contractbridge', players: '' },
  { name: 'Dickory', url: '/gamepanel?game=dickory', players: '' },
  { name: 'Sahwari', url: '/gamepanel?game=sahwari', players: '' },
  { name: 'Block Arena', url: '/gamepanel?game=blockarena', players: '' },
  { name: 'Dice Mission', url: '/gamepanel?game=dicemission', players: '' },
  { name: 'Guile', url: '/gamepanel?game=guile', players: '' },
  { name: 'Bayonets & Tomahawks', url: '/gamepanel?game=bayonetsandtomahawks', players: '' },
  { name: 'Diamonds', url: '/gamepanel?game=diamonds', players: '' },
  { name: '1000', url: '/gamepanel?game=thousand', players: '' },
  { name: 'Reflections in the Looking Glass', url: '/gamepanel?game=reflectionsinthelookingglass', players: '' },
  { name: 'Monster Hex', url: '/gamepanel?game=monsterhex', players: '' },
  { name: 'Trench', url: '/gamepanel?game=trench', players: '' },
  { name: 'German Whist', url: '/gamepanel?game=germanwhist', players: '' },
  { name: 'Biomes of Nilgiris', url: '/gamepanel?game=biomesofnilgiris', players: '' },
  { name: 'Impasse', url: '/gamepanel?game=impasse', players: '' },
  { name: 'Kani Nari Ebi', url: '/gamepanel?game=kaninariebi', players: '' },
  { name: 'Onda', url: '/gamepanel?game=onda', players: '' },
  { name: 'Bunny Drops', url: '/gamepanel?game=bunnydrops', players: '' },
  { name: 'the itty bitty card game', url: '/gamepanel?game=theittybittycardgame', players: '' },
  { name: 'Blast Radius', url: '/gamepanel?game=blastradius', players: '' },
  { name: 'Redstone', url: '/gamepanel?game=redstone', players: '' },
  { name: 'Carpniches', url: '/gamepanel?game=carpniches', players: '' },
  { name: 'Misty', url: '/gamepanel?game=misty', players: '' },
  { name: 'Stonks', url: '/gamepanel?game=stonks', players: '' },
  { name: 'Gravity Superstar', url: '/gamepanel?game=gravitysuperstar', players: '' },
  { name: 'Cuttle', url: '/gamepanel?game=cuttle', players: '' },
  { name: 'Bauer', url: '/gamepanel?game=bauer', players: '' },
  { name: 'Massive-Verse: Fighting Card Game', url: '/gamepanel?game=massiveverse', players: '' },
  { name: 'Factum', url: '/gamepanel?game=factum', players: '' },
  { name: 'Mexica', url: '/gamepanel?game=mexica', players: '' },
  { name: 'Cannonades', url: '/gamepanel?game=cannonades', players: '' },
  { name: 'River Rats', url: '/gamepanel?game=riverrats', players: '' },
  { name: 'The Nine Domains', url: '/gamepanel?game=theninedomains', players: '' },
  { name: 'Cassino', url: '/gamepanel?game=cassino', players: '' },
  { name: 'Galactic Era', url: '/gamepanel?game=galacticera', players: '' },
  { name: 'Pedro', url: '/gamepanel?game=pedro', players: '' },
  { name: 'Fibonachos', url: '/gamepanel?game=fibonachos', players: '' },
  { name: 'Lineae', url: '/gamepanel?game=lineae', players: '' },
  { name: 'Caribbean All Fours', url: '/gamepanel?game=caribbeanallfours', players: '' },
  { name: 'Phat', url: '/gamepanel?game=phat', players: '' },
  { name: 'HUND', url: '/gamepanel?game=hund', players: '' },
  { name: 'Fled', url: '/gamepanel?game=fled', players: '' },
  { name: 'Crash', url: '/gamepanel?game=crash', players: '' },
  { name: 'Piratas!', url: '/gamepanel?game=piratas', players: '' },
  { name: 'Divercit�', url: '/gamepanel?game=divercite', players: '' },
  { name: 'Mate', url: '/gamepanel?game=mate', players: '' },
  { name: 'Tholos', url: '/gamepanel?game=tholos', players: '' },
  { name: 'Hamsters vs Hippos', url: '/gamepanel?game=hamstersvshippos', players: '' },
  { name: 'Falconry', url: '/gamepanel?game=falconry', players: '' },
  { name: 'M�', url: '/gamepanel?game=mue', players: '' },
  { name: 'Metz', url: '/gamepanel?game=metz', players: '' },
  { name: 'Skirmish: Battle for Draconia', url: '/gamepanel?game=skirmishbattlefordraconia', players: '' },
  { name: 'Livingstone', url: '/gamepanel?game=livingstone', players: '' },
  { name: 'Kingdoms', url: '/gamepanel?game=kingdoms', players: '' },
  { name: 'Savanna Ten', url: '/gamepanel?game=savannaten', players: '' },
  { name: 'Battlegammon', url: '/gamepanel?game=battlegammon', players: '' },
  { name: 'Nap', url: '/gamepanel?game=nap', players: '' },
  { name: 'Molly House', url: '/gamepanel?game=mollyhouse', players: '' },
  { name: 'Grosstarock', url: '/gamepanel?game=grosstarock', players: '' },
  { name: 'All In', url: '/gamepanel?game=allin', players: '' },
  { name: 'Queens & Kings... A Checkers Game', url: '/gamepanel?game=queenskings', players: '' },
  { name: 'Hachihachi', url: '/gamepanel?game=eightyeight', players: '' },
  { name: '500', url: '/gamepanel?game=fivehundred', players: '' },
  { name: 'Quadrata Canada', url: '/gamepanel?game=quadratacanada', players: '' },
  { name: 'Jewel Box', url: '/gamepanel?game=jewelbox', players: '' },
  { name: 'Stigm�ria', url: '/gamepanel?game=stigmeria', players: '' },
  { name: 'Auntie Mildred\'s list of random tasks', url: '/gamepanel?game=auntiemildred', players: '' },
  { name: 'Golems', url: '/gamepanel?game=golems', players: '' },
  { name: 'Monster Smash', url: '/gamepanel?game=monstersmash', players: '' },
  { name: 'Seven Knights Bewitched', url: '/gamepanel?game=sevenknightsbewitched', players: '' },
  { name: 'Nirds', url: '/gamepanel?game=nirds', players: '' },
  { name: 'Jokerball', url: '/gamepanel?game=jokerball', players: '' },
  { name: 'Congkak', url: '/gamepanel?game=congkak', players: '' },
  { name: 'Shokoba', url: '/gamepanel?game=shokoba', players: '' },
  { name: 'Good Fortune', url: '/gamepanel?game=goodfortune', players: '' },
  { name: 'Enemy Anemone', url: '/gamepanel?game=enemyanemone', players: '' },
  { name: 'Whist', url: '/gamepanel?game=whist', players: '' },
  { name: 'Alakablast', url: '/gamepanel?game=alakablast', players: '' },
  { name: 'Monster Trick', url: '/gamepanel?game=monstertrick', players: '' },
  { name: 'Lunar', url: '/gamepanel?game=lunar', players: '' },
  { name: 'Megalomania', url: '/gamepanel?game=megalomania', players: '' },
  { name: 'Dance of Muses', url: '/gamepanel?game=danceofmuses', players: '' },
  { name: 'Trickarus', url: '/gamepanel?game=trickarus', players: '' },
  { name: 'Amoriax', url: '/gamepanel?game=amoriax', players: '' },
  { name: 'Circle Of Life: on the Savannah', url: '/gamepanel?game=circleoflifesavannah', players: '' },
  { name: 'Blaze', url: '/gamepanel?game=blaze', players: '' },
  { name: 'Aiy�', url: '/gamepanel?game=aiye', players: '' },
  { name: 'Scriptoria', url: '/gamepanel?game=scriptoria', players: '' },
  { name: 'TriATri', url: '/gamepanel?game=triatri', players: '' },
  { name: 'Sneferu: Builders of the Pyramids', url: '/gamepanel?game=sneferu', players: '' },
  { name: 'Starship Merchants', url: '/gamepanel?game=starshipmerchants', players: '' },
  { name: 'Batalla de Coronas', url: '/gamepanel?game=batalladecoronas', players: '' },
  { name: 'H?i Ph? (Second Edition)', url: '/gamepanel?game=hoipho', players: '' },
  { name: 'Bebop', url: '/gamepanel?game=bebop', players: '' },
  { name: 'Micro Midgard', url: '/gamepanel?game=micromidgard', players: '' },
  { name: 'Aurum', url: '/gamepanel?game=aurum', players: '' },
  { name: '13 Leaves', url: '/gamepanel?game=thirteenleaves', players: '' },
  { name: '42', url: '/gamepanel?game=fortytwo', players: '' },
  { name: 'Tulip & Rose', url: '/gamepanel?game=tulipandrose', players: '' },
  { name: 'Rumble Planet', url: '/gamepanel?game=rumbleplanet', players: '' },
  { name: 'Love Links', url: '/gamepanel?game=lovelinks', players: '' },
  { name: 'Postcards', url: '/gamepanel?game=postcards', players: '' },
  { name: 'Shock! Knights & Poisons', url: '/gamepanel?game=shock', players: '' },
  { name: 'Norsemen', url: '/gamepanel?game=norsemen', players: '' },
  { name: 'Sunrise Sunset', url: '/gamepanel?game=sunrisesunset', players: '' },
  { name: 'Natural Chaos', url: '/gamepanel?game=naturalchaos', players: '' },
  { name: 'Sergeant Major', url: '/gamepanel?game=sergeantmajor', players: '' },
  { name: 'KQJ', url: '/gamepanel?game=kqj', players: '' },
  { name: 'Deck EXPRESS: Tennessee Central', url: '/gamepanel?game=deckexpresstennesseecentral', players: '' },
  { name: 'TEMBO: Survival on the Savanna', url: '/gamepanel?game=tembo', players: '' },
  { name: 'Safari Witness', url: '/gamepanel?game=safariwitness', players: '' },
  { name: 'Sasaki', url: '/gamepanel?game=sasaki', players: '' },
  { name: 'Strategic Reserve', url: '/gamepanel?game=strategicreserve', players: '' },
  { name: 'Pisanki', url: '/gamepanel?game=pisanki', players: '' },
  { name: 'Coins', url: '/gamepanel?game=coins', players: '' },
  { name: 'Blot', url: '/gamepanel?game=blot', players: '' },
  { name: 'The Nine sons of dragon', url: '/gamepanel?game=theninesonsofthedragon', players: '' },
  { name: 'Space Lab', url: '/gamepanel?game=spacelab', players: '' },
  { name: 'Malabares', url: '/gamepanel?game=malabares', players: '' },
  { name: 'Persona Non Grata', url: '/gamepanel?game=personanongrata', players: '' },
  { name: 'Fox on the Tree', url: '/gamepanel?game=foxonthetree', players: '' },
  { name: 'Two-Ten-Jack', url: '/gamepanel?game=twotenjack', players: '' },
  { name: 'Schafkopf', url: '/gamepanel?game=schafkopf', players: '' },
  { name: 'GhostsGalore', url: '/gamepanel?game=ghostsgalore', players: '' },
  { name: 'Crash & Grab', url: '/gamepanel?game=crashandgrab', players: '' },
  { name: 'Perikles', url: '/gamepanel?game=perikles', players: '' },
  { name: 'Grund', url: '/gamepanel?game=grund', players: '' },
  { name: 'Cookie Battle', url: '/gamepanel?game=cookiebattle', players: '' },
  { name: 'Paiko', url: '/gamepanel?game=paiko', players: '' },
  { name: 'Minnesota Whist', url: '/gamepanel?game=minnesotawhist', players: '' },
  { name: 'Olenon', url: '/gamepanel?game=olenon', players: '' },
  { name: 'Troggu', url: '/gamepanel?game=troggu', players: '' },
  { name: 'Pyrotechnics', url: '/gamepanel?game=pyrotechnics', players: '' },
  { name: 'Ynaros Fallin', url: '/gamepanel?game=ynarosfallin', players: '' },
  { name: 'Calypso', url: '/gamepanel?game=calypso', players: '' },
  { name: 'Raubbau', url: '/gamepanel?game=raubbau', players: '' },
  { name: 'Vizia', url: '/gamepanel?game=vizia', players: '' },
  { name: 'Cry Baby', url: '/gamepanel?game=crybaby', players: '' },
  { name: 'Kaiser', url: '/gamepanel?game=kaiser', players: '' },
  { name: 'Aniversus', url: '/gamepanel?game=aniversus', players: '' },
  { name: 'Quintus', url: '/gamepanel?game=quintus', players: '' },
];

const KNOWN_FREE_GAMES = BASE_KNOWN_GAMES.map(enrichGame);

// Attempt live scrape first; fall back to curated list on failure.
async function scrapeFreeGames() {
  try {
    const games = await scrapeFromBGA();
    if (games.length > 0) return games.map(enrichGame);
  } catch (err) {
    console.warn('BGA scraping failed, using known list:', err.message);
  }
  return KNOWN_FREE_GAMES;
}

// Attempt to scrape BGA's game list pages for non-premium games.
// Tries multiple URLs because BGA's structure varies by region/session.
// The premium detection heuristic is fragile — BGA doesn't expose
// premium status in a stable DOM attribute, so we look for crown
// icons and "premium" class names. This often fails silently, which
// is why the curated list exists as a fallback.
async function scrapeFromBGA() {
  const urls = [
    'https://boardgamearena.com/gamelist?section=all',
    'https://boardgamearena.com/games',
    'https://boardgamearena.com/gamelist',
  ];

  for (const url of urls) {
    try {
      const resp = await axios.get(url, {
        headers: { 'User-Agent': USER_AGENT, 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5' },
        timeout: 15000,
        maxRedirects: 0,
        validateStatus: s => s < 400,
      });

      const $ = cheerio.load(resp.data);
      const games = [];
      const seen = new Set();

      $('a[href*="gamepanel?game="]').each((i, el) => {
        const href = $(el).attr('href') || '';
        const match = href.match(/gamepanel\?game=([^&]+)/);
        if (match && !seen.has(match[1])) {
          seen.add(match[1]);
          const isPremium = $(el).closest('*').find('[class*="premium"], [class*="crown"], .fa-crown').length > 0 ||
            $(el).text().toLowerCase().includes('premium');
          if (!isPremium) {
            const name = $(el).text().trim() || $(el).find('img').first().attr('alt') || match[1];
            games.push({ name, url: '/gamepanel?game=' + match[1], players: '' });
          }
        }
      });

      if (games.length > 0) return games;
    } catch (e) {
      continue;
    }
  }
  return [];
}

function getAllGenres() {
  const set = new Set();
  for (const g of KNOWN_FREE_GAMES) {
    if (g.genres) g.genres.forEach(gn => set.add(gn));
  }
  return [...set].sort();
}

module.exports = { scrapeFreeGames, scrapeFromBGA, KNOWN_FREE_GAMES, getAllGenres, enrichGame };
